# Generated by Django 4.1.10 on 2023-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mensajes_likescomments_historias'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
