# Generated by Django 4.1.10 on 2023-09-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posts_like_posts_likeusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userimage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='userimage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
