# Generated by Django 4.1.10 on 2023-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mensajes_image_mensajes_username_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historias',
            name='userimage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historias',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
