# Generated by Django 4.1.10 on 2023-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_historias_userimage_historias_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePerfil', models.ImageField(blank=True, null=True, upload_to='images/perfil/')),
                ('imagePortada', models.ImageField(blank=True, null=True, upload_to='images/portada/')),
            ],
        ),
    ]
