# Generated by Django 4.1.10 on 2023-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/grupos/'),
        ),
        migrations.AlterField(
            model_name='historias',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/historias/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/'),
        ),
    ]
